### ISSUE TITLE
Ghost number in status overlay

### ISSUE THREAD

**Issue by danielthedifficult** [windusayles/slotty-machine#2]
<img width="484" alt="Screenshot 2023-11-14 at 12 02 47 PM" src="https://github.com/windusayles/slotty-machine/assets/1290033/cfd5ef1a-17b8-40ff-9a20-29db5b839fa7">

Repro:
1. Start a new game
2. Wager once with default wager (2)
3. next round, change wager and spin
4. Zoom in on the wager number

**Comment by windusayles** [comment]
@danielthedifficult I just needed to update the text, but I was generating the text box each time (hence ghost behind).
